"""
JEP CLI — jep web, jep verify, jep export (causal report)
"""

import json
import click
from pathlib import Path
from rich.console import Console
from rich.table import Table

console = Console()


@click.group()
def cli():
    """JEP-Agent SDK CLI v1.0"""
    pass


@cli.command()
@click.option("--port", default=8080, help="Web viewer port")
@click.option("--host", default="127.0.0.1", help="Bind host")
@click.option("--reload", is_flag=True, help="Auto-reload")
def web(port, host, reload):
    """Launch the causal web viewer."""
    from jep.web.server import start_server
    console.print(f"[bold green]JEP Causal Viewer[/bold green] http://{host}:{port}")
    start_server(host=host, port=port, reload=reload)


@cli.command()
@click.argument("file", type=click.Path(exists=True))
@click.option("--public-key", type=click.Path(exists=True), help="Ed25519 public key PEM")
@click.option("--aud", help="Expected audience")
def verify(file, public_key, aud):
    """Verify JEP events (signature, chain, replay)."""
    from jep.core.verifier import JEPVerifier
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
    from cryptography.hazmat.primitives import serialization
    
    verifier = JEPVerifier()
    pk = None
    if public_key:
        with open(public_key, "rb") as f:
            pk = serialization.load_pem_public_key(f.read())
    
    events = []
    with open(file, "r") as f:
        events = [json.loads(line) for line in f if line.strip()]
    
    table = Table(title="JEP Verification Results")
    table.add_column("Verb", style="cyan")
    table.add_column("Nonce", style="dim")
    table.add_column("Result", style="bold")
    
    valid = invalid = 0
    for ev in events:
        result = verifier.verify(ev, public_key=pk, expected_aud=aud)
        color = "green" if result == "VALID" else "yellow" if "FAULT" in result else "red"
        table.add_row(ev.get("verb", "?"), ev["nonce"][:8], f"[{color}]{result}[/{color}]")
        if result == "VALID": valid += 1
        else: invalid += 1
    
    console.print(table)
    console.print(f"[bold]Events: {len(events)} | Valid: {valid} | Invalid: {invalid}[/bold]")


@cli.command()
@click.argument("file", type=click.Path(exists=True))
@click.option("--output", "-o", required=True, help="Output HTML path")
@click.option("--title", default="JEP Audit Report", help="Report title")
def export(file, output, title):
    """Export a full causal audit report (HTML with embedded graph)."""
    events = []
    with open(file, "r") as f:
        events = [json.loads(line) for line in f if line.strip()]
    
    html = _generate_full_report(events, title)
    with open(output, "w", encoding="utf-8") as f:
        f.write(html)
    console.print(f"[green]Report exported: {output} ({len(events)} events)[/green]")


def _generate_full_report(events, title):
    nodes_json = json.dumps([{
        "id": e.get("event_id", i),
        "verb": e.get("verb"),
        "who": e.get("who"),
        "when": e.get("when"),
        "what": str(e.get("what", ""))[:80],
        "nonce": e.get("nonce"),
        "ref": e.get("ref"),
        "task_based_on": e.get("task_based_on"),
        "sig": bool(e.get("sig")),
    } for i, e in enumerate(events)])
    
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"><title>{title}</title>
<style>
body{{font-family:system-ui,-apple-system,sans-serif;background:#0b0f19;color:#e2e8f0;margin:0;}}
.header{{padding:32px;border-bottom:1px solid #1e293b;}}
.header h1{{margin:0;font-size:24px;}}
.header p{{margin:8px 0 0;color:#64748b;font-size:14px;}}
.stats{{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;padding:24px 32px;}}
.card{{background:#0f172a;border:1px solid #1e293b;border-radius:8px;padding:20px;}}
.card .label{{font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:8px;}}
.card .value{{font-size:32px;font-weight:700;color:#f8fafc;}}
.section{{padding:0 32px 32px;}}
.section h2{{font-size:16px;margin-bottom:16px;color:#94a3b8;}}
table{{width:100%;border-collapse:collapse;font-size:13px;}}
th{{text-align:left;padding:10px;background:#0f172a;color:#94a3b8;border-bottom:1px solid #334155;}}
td{{padding:10px;border-bottom:1px solid #1e293b;word-break:break-all;}}
td.mono{{font-family:monospace;font-size:11px;color:#cbd5e1;}}
.badge{{display:inline-block;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:600;}}
.badge-J{{background:#dbeafe;color:#1e40af;}}
.badge-D{{background:#fef3c7;color:#92400e;}}
.badge-T{{background:#fee2e2;color:#991b1b;}}
.badge-V{{background:#dcfce7;color:#166534;}}
#graph{{width:100%;height:500px;background:#0b0f19;border:1px solid #1e293b;border-radius:8px;margin-bottom:32px;}}
</style>
</head>
<body>
<div class="header"><h1>{title}</h1><p>Generated by JEP-Agent SDK v1.0 | {len(events)} events</p></div>
<div class="stats">
<div class="card"><div class="label">Total Events</div><div class="value">{len(events)}</div></div>
<div class="card"><div class="label">Signed</div><div class="value">{sum(1 for e in events if e.get('sig'))}</div></div>
<div class="card"><div class="label">Chains</div><div class="value">{len(set(e.get('ref') for e in events if e.get('ref')))}</div></div>
<div class="card"><div class="label">Cross-Agent</div><div class="value">{sum(1 for e in events if e.get('task_based_on'))}</div></div>
</div>
<div class="section">
<h2>Causal Topology</h2>
<svg id="graph"></svg>
</div>
<div class="section">
<h2>Event Log</h2>
<table>
<tr><th>Verb</th><th>Who</th><th>When</th><th>What</th><th>Ref</th><th>Signed</th></tr>
{''.join(f"<tr><td><span class='badge badge-{e.get('verb','?')}'>{e.get('verb','?')}</span></td><td>{e.get('who','')}</td><td>{e.get('when','')}</td><td class='mono'>{str(e.get('what',''))[:60]}</td><td class='mono'>{str(e.get('ref',''))[:20]}</td><td>{'✓' if e.get('sig') else '—'}</td></tr>" for e in events)}
</table>
</div>
<script>
const nodes = {nodes_json};
const links = [];
const nodeMap = new Map();
nodes.forEach((n,i) => nodeMap.set(n.id, i));
nodes.forEach((n,i) => {{
    if(n.ref && nodeMap.has(n.ref)) links.push({{source:nodeMap.get(n.ref), target:i, type:'ref'}});
    if(n.task_based_on && nodeMap.has(n.task_based_on)) links.push({{source:nodeMap.get(n.task_based_on), target:i, type:'task'}});
}});
const svg = document.getElementById('graph');
const width = svg.clientWidth || 800;
const height = 500;
svg.setAttribute('viewBox', `0 0 ${{width}} ${{height}}`);
const colors = {{J:'#60a5fa', D:'#fbbf24', T:'#f87171', V:'#34d399'}};
for(let iter=0; iter<200; iter++) {{
    for(let i=0;i<nodes.length;i++) {{
        for(let j=i+1;j<nodes.length;j++) {{
            const dx=nodes[j].x-nodes[i].x, dy=nodes[j].y-nodes[i].y, dist=Math.sqrt(dx*dx+dy*dy)||1;
            const f=3000/(dist*dist), fx=(dx/dist)*f;
            nodes[i].vx=(nodes[i].vx||0)-fx; nodes[i].vy=(nodes[i].vy||0)-(dy/dist)*f;
            nodes[j].vx=(nodes[j].vx||0)+fx; nodes[j].vy=(nodes[j].vy||0)+(dy/dist)*f;
        }}
    }}
    links.forEach(l => {{
        const dx=nodes[l.target].x-nodes[l.source].x, dy=nodes[l.target].y-nodes[l.source].y;
        const dist=Math.sqrt(dx*dx+dy*dy)||1, f=(dist-100)*0.03;
        nodes[l.source].vx+= (dx/dist)*f; nodes[l.source].vy+= (dy/dist)*f;
        nodes[l.target].vx-= (dx/dist)*f; nodes[l.target].vy-= (dy/dist)*f;
    }});
    nodes.forEach(n => {{
        n.vx=(n.vx||0)+(width/2-n.x)*0.003; n.vy=(n.vy||0)+(height/2-n.y)*0.003;
        n.x+=n.vx; n.y+=n.vy; n.vx*=0.5; n.vy*=0.5;
        if(!n.x) n.x=width/2+(Math.random()-0.5)*300;
        if(!n.y) n.y=height/2+(Math.random()-0.5)*300;
    }});
}}
links.forEach(l => {{
    const line=document.createElementNS('http://www.w3.org/2000/svg','line');
    line.setAttribute('x1',nodes[l.source].x); line.setAttribute('y1',nodes[l.source].y);
    line.setAttribute('x2',nodes[l.target].x); line.setAttribute('y2',nodes[l.target].y);
    line.setAttribute('stroke',l.type==='task'?'#a78bfa':'#475569');
    line.setAttribute('stroke-width',l.type==='task'?2:1);
    line.setAttribute('stroke-dasharray',l.type==='task'?'4,4':'none');
    svg.appendChild(line);
}});
nodes.forEach(n => {{
    const c=document.createElementNS('http://www.w3.org/2000/svg','circle');
    c.setAttribute('cx',n.x); c.setAttribute('cy',n.y); c.setAttribute('r',n.task_based_on?12:8);
    c.setAttribute('fill',colors[n.verb]||'#94a3b8');
    c.setAttribute('stroke',n.task_based_on?'#a78bfa':'#0b0f19');
    c.setAttribute('stroke-width',n.task_based_on?2:1);
    svg.appendChild(c);
}});
</script>
</body>
</html>"""
